### PR TITLE
New VAPI in feature checklist.

### PR DESCRIPTION
**Pull request by judy2k**

### CODE REVIEW

**Comment by leggetter** [comment]
@judy2k - worth consolidating with https://github.com/Nexmo/client-library-specification/tree/new-voice-api-readme/templates#api-coverage

I'd also suggest we clarify that with webhooks we're generally talking about validating that they are correctly formed and have come from Nexmo. The latter may require a bit of digging and chatting with product.

I also personally think that offering outbound API request functionality (e.g. make a call) is of higher priority than handling inbound webhook validation. Maybe that should be reflected in some way?

**Comment by leggetter** [comment]
> I also personally think that offering outbound API request functionality (e.g. make a call) is of higher priority than handling inbound webhook validation. Maybe that should be reflected in some way?

It may even be worth updating the checklist into two sections. Inbound/Outbound? Something that clearly states that the main functionality is present and the inbound/webhook stuff is optional. I've had somebody speak to me thinking that a library was falling short simply because the webhook functionality wasn't present. I don't think that's a true reflection.

**Comment by judy2k** [comment]
@leggetter That branch you've linked to is *this* branch. Or have I missed something?

**Comment by judy2k** [comment]
Requested a review from @sammachin

**Comment by leggetter** [comment]
> @leggetter That branch you've linked to is this branch. Or have I missed something?

Yep. Whoops!

**Comment by sammachin** [comment]
I'm merging this for now but I'm also in  the process of re-writing the feature checklist into YAML with better descriptions of each feature but this is useful input for that

**Pull request merged**
